-- Migration 012 : Motif de départ collaborateur
ALTER TABLE employees
  ADD COLUMN IF NOT EXISTS departure_reason VARCHAR(50) DEFAULT NULL;

-- VALEURS : NOUVELLES_OPPORTUNITES | RAISONS_PERSONNELLES | REMUNERATION | MANAGEMENT | AUTRES
COMMENT ON COLUMN employees.departure_reason IS 'Motif de départ : NOUVELLES_OPPORTUNITES, RAISONS_PERSONNELLES, REMUNERATION, MANAGEMENT, AUTRES';
